/*
 * This file was automatically generated by EvoSuite
 * Wed May 13 19:17:49 GMT 2026
 * Adapted for PIT compatibility (removed EvoRunner dependency)
 */

package org.apache.zookeeper.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.zookeeper.common.PathTrie;

public class PathTrie_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      String string0 = pathTrie0.findMaxPrefix("M2\u0003/TVCxUPxv");
      assertEquals("/", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("M2\u0003/TVCxUPxv");
      boolean boolean0 = pathTrie0.existsNode("M2\u0003/TVCxUPxv");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      try {
        pathTrie0.existsNode("");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        assertTrue(e.getMessage().contains("Invalid path"));
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.deletePath("uLW(,");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      try {
        pathTrie0.deletePath("");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        assertTrue(e.getMessage().contains("Invalid path"));
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("M2\u0003/TVCxUPxv");
      pathTrie0.addPath("M2\u0003/TVCxUPxv");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      try {
        pathTrie0.addPath("");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        assertTrue(e.getMessage().contains("Invalid path"));
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("M2\u0003/TVCxUPxv");
      String string0 = pathTrie0.findMaxPrefix("M2\u0003/TVCxUPxv");
      assertEquals("/M2\u0003/TVCxUPxv", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("uLW(,");
      pathTrie0.deletePath("uLW(,");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      boolean boolean0 = pathTrie0.existsNode("u`z.`/}3gLu_$");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.clear();
  }
}