/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 08:12:41 GMT 2026
 */

package org.apache.zookeeper.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.zookeeper.common.PathTrie;

public class PathTrieC4_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      String string0 = pathTrie0.findMaxPrefix("gA=}jF,Fq,w");
      assertEquals("/", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("$w>9%l7$,T<_/\"1Bq");
      boolean boolean0 = pathTrie0.existsNode("$w>9%l7$,T<_/\"1Bq");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      // Undeclared exception!
      try { 
        pathTrie0.existsNode("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid path: 
         //
         // Expected
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      boolean boolean0 = pathTrie0.existsNode("$w>9%l7$,T<_/\"1Bq");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      // Undeclared exception!
      try { 
        pathTrie0.deletePath("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid path: 
         //
         // Expected
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("$w>9%l7$,T<_/\"1Bq");
      pathTrie0.addPath("$w>9%l7$,T<_/\"1Bq");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      // Undeclared exception!
      try { 
        pathTrie0.addPath("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid path: 
         //
         // Expected
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("gA=}jF,Fq,w");
      pathTrie0.deletePath("gA=}jF,Fq,w");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("$w>9%l7$,T<_/\"1Bq");
      String string0 = pathTrie0.findMaxPrefix("$w>9%l7$,T<_/\"1Bq");
      assertEquals("/$w>9%l7$,T<_/\"1Bq", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.deletePath("$w>9%l7$,T<_/\"1Bq");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.clear();
  }
}
