/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 08:03:30 GMT 2026
 */

package org.apache.zookeeper.common;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.zookeeper.common.PathTrie;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PathTrie_ESTest extends PathTrie_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      String string0 = pathTrie0.findMaxPrefix("L6iyNN6:\"*");
      assertEquals("/", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("nw[ym");
      boolean boolean0 = pathTrie0.existsNode("nw[ym");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      // Undeclared exception!
      try { 
        pathTrie0.existsNode("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid path: 
         //
         verifyException("org.apache.zookeeper.common.PathTrie", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      boolean boolean0 = pathTrie0.existsNode("nw[ym");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.deletePath("!");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      // Undeclared exception!
      try { 
        pathTrie0.deletePath("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid path: 
         //
         verifyException("org.apache.zookeeper.common.PathTrie", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("nw[ym");
      pathTrie0.addPath("nw[ym");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      // Undeclared exception!
      try { 
        pathTrie0.addPath("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid path: 
         //
         verifyException("org.apache.zookeeper.common.PathTrie", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("ip[/Jg$>|Pphp*i5G}");
      String string0 = pathTrie0.findMaxPrefix("ip[/Jg$>|Pphp*i5G}");
      assertEquals("/ip[/Jg$>|Pphp*i5G}", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.addPath("L6iyNN6:\"*");
      pathTrie0.deletePath("L6iyNN6:\"*");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PathTrie pathTrie0 = new PathTrie();
      pathTrie0.clear();
  }
}
