// File generated by hadoop record compiler. Do not edit.

#ifndef AuthPacket_HH_
#define AuthPacket_HH_

#include "Efc.hh"
#include "../../jute/inc/ERecord.hh"
#include "../../jute/inc/EBinaryInputArchive.hh"
#include "../../jute/inc/EBinaryOutputArchive.hh"
#include "../../jute/inc/ECsvOutputArchive.hh"

namespace efc {
namespace ezk {

class AuthPacket: public ERecord {
public:
	int type;
	EString scheme;
	sp<EA<byte> > auth;

	AuthPacket() {
	}
	AuthPacket(int type, EString scheme, sp<EA<byte> > auth) {
		this->type = type;
		this->scheme = scheme;
		this->auth = auth;
	}
	int getType() {
		return type;
	}
	void setType(int m_) {
		type = m_;
	}
	EString getScheme() {
		return scheme;
	}
	void setScheme(EString m_) {
		scheme = m_;
	}
	sp<EA<byte> > getAuth() {
		return auth;
	}
	void setAuth(sp<EA<byte> > m_) {
		auth = m_;
	}
	virtual void serialize(EOutputArchive* a_, const char* tag)
			THROWS(EIOException) {
		a_->startRecord(this, tag);
		a_->writeInt(type, "type");
		a_->writeString(scheme, "scheme");
		a_->writeBuffer(auth.get(), "auth");
		a_->endRecord(this, tag);
	}
	virtual void deserialize(EInputArchive* a_, const char* tag)
			THROWS(EIOException) {
		a_->startRecord(tag);
		type = a_->readInt("type");
		scheme = a_->readString("scheme");
		auth = a_->readBuffer("auth");
		a_->endRecord(tag);
	}
	virtual EString toString() {
		try {
			EByteArrayOutputStream s;
			ECsvOutputArchive a_(&s);
			a_.startRecord(this, "");
			a_.writeInt(type, "type");
			a_.writeString(scheme, "scheme");
			a_.writeBuffer(auth.get(), "auth");
			a_.endRecord(this, "");
			s.write('\0');
			return (char*) s.data();
		} catch (EThrowable& ex) {
			ex.printStackTrace();
		}
		return "ERROR";
	}
	void write(EDataOutput* out) THROWS(EIOException) {
		EBinaryOutputArchive archive(out);
		serialize(&archive, "");
	}
	void readFields(EDataInput* in) THROWS(EIOException) {
		EBinaryInputArchive archive(in);
		deserialize(&archive, "");
	}
	virtual int compareTo(EObject* peer_) THROWS(EClassCastException) {
		AuthPacket* peer = dynamic_cast<AuthPacket*>(peer_);
		if (!peer) {
			throw EClassCastException(__FILE__, __LINE__,
					"Comparing different types of records.");
		}
		int ret = 0;
		ret = (type == peer->type) ? 0 : ((type < peer->type) ? -1 : 1);
		if (ret != 0)
			return ret;
		ret = scheme.compareTo(&peer->scheme);
		if (ret != 0)
			return ret;
		{
			sp<EA<byte> > my = auth;
			sp<EA<byte> > ur = peer->auth;
			ret = compareBytes(my.get(), 0, my->length(), ur.get(), 0,
					ur->length());
		}
		if (ret != 0)
			return ret;
		return ret;
	}
	virtual boolean equals(EObject* peer_) {
		AuthPacket* peer = dynamic_cast<AuthPacket*>(peer_);
		if (!peer) {
			return false;
		}
		if (peer_ == this) {
			return true;
		}
		boolean ret = false;
		ret = (type == peer->type);
		if (!ret)
			return ret;
		ret = scheme.equals(peer->scheme);
		if (!ret)
			return ret;
		ret = bufEquals(auth.get(), peer->auth.get());
		if (!ret)
			return ret;
		return ret;
	}
	virtual int hashCode() {
		int result = 17;
		int ret;
		ret = (int) type;
		result = 37 * result + ret;
		ret = scheme.hashCode();
		result = 37 * result + ret;
		ret = EArrays::toString(auth.get()).hashCode();
		result = 37 * result + ret;
		return result;
	}
	static EString signature() {
		return "LAuthPacket(isB)";
	}
};

} /* namespace ezk */
} /* namespace efc */
#endif /* AuthPacket_HH_ */
