// File generated by hadoop record compiler. Do not edit.

#ifndef CreateRequest_HH_
#define CreateRequest_HH_

#include "Efc.hh"
#include "../../jute/inc/ERecord.hh"
#include "../../jute/inc/EBinaryInputArchive.hh"
#include "../../jute/inc/EBinaryOutputArchive.hh"
#include "../../jute/inc/ECsvOutputArchive.hh"
#include "../data/ACL.hh"

namespace efc {
namespace ezk {

class CreateRequest: public ERecord {
public:
	EString path;
	sp<EA<byte> > data;
	sp<EList<sp<ACL> > > acl;
	int flags;

	CreateRequest() {
	}
	CreateRequest(EString path, sp<EA<byte> > data, sp<EList<sp<ACL> > > acl,
			int flags) {
		this->path = path;
		this->data = data;
		this->acl = acl;
		this->flags = flags;
	}
	EString getPath() {
		return path;
	}
	void setPath(EString m_) {
		path = m_;
	}
	sp<EA<byte> > getData() {
		return data;
	}
	void setData(sp<EA<byte> > m_) {
		data = m_;
	}
	sp<EList<sp<ACL> > > getAcl() {
		return acl;
	}
	void setAcl(sp<EList<sp<ACL> > > m_) {
		acl = m_;
	}
	int getFlags() {
		return flags;
	}
	void setFlags(int m_) {
		flags = m_;
	}
	virtual void serialize(EOutputArchive* a_, const char* tag)
			THROWS(EIOException) {
		a_->startRecord(this, tag);
		a_->writeString(path, "path");
		a_->writeBuffer(data.get(), "data");
		{
			a_->startVector(acl.get(), JUTE_SIZE(acl), "acl");
			if (acl != null) {
				int len1 = acl->size();
				for (int vidx1 = 0; vidx1 < len1; vidx1++) {
					ACL* e1 = dynamic_cast<ACL*>(acl->getAt(vidx1).get());
					a_->writeRecord(e1, "e1");
				}
			}
			a_->endVector(acl.get(), "acl");
		}
		a_->writeInt(flags, "flags");
		a_->endRecord(this, tag);
	}
	virtual void deserialize(EInputArchive* a_, const char* tag)
			THROWS(EIOException) {
		a_->startRecord(tag);
		path = a_->readString("path");
		data = a_->readBuffer("data");
		{
			sp<EIndex> vidx1 = a_->startVector("acl");
			if (vidx1 != null) {
				acl = new EArrayList<sp<ACL> >();
				for (; !vidx1->done(); vidx1->incr()) {
					sp<ACL> e1 = new ACL();
					a_->readRecord(e1.get(), "e1");
					acl->add(e1);
				}
			}
			a_->endVector("acl");
		}
		flags = a_->readInt("flags");
		a_->endRecord(tag);
	}
	virtual EString toString() {
		try {
			EByteArrayOutputStream s;
			ECsvOutputArchive a_(&s);
			a_.startRecord(this, "");
			a_.writeString(path, "path");
			a_.writeBuffer(data.get(), "data");
			{
				a_.startVector(acl.get(), JUTE_SIZE(acl), "acl");
				if (acl != null) {
					int len1 = acl->size();
					for (int vidx1 = 0; vidx1 < len1; vidx1++) {
						ACL* e1 = dynamic_cast<ACL*>(acl->getAt(vidx1).get());
						a_.writeRecord(e1, "e1");
					}
				}
				a_.endVector(acl.get(), "acl");
			}
			a_.writeInt(flags, "flags");
			a_.endRecord(this, "");
			s.write('\0');
			return (char*) s.data();
		} catch (EThrowable& ex) {
			ex.printStackTrace();
		}
		return "ERROR";
	}
	void write(EDataOutput* out) THROWS(EIOException) {
		EBinaryOutputArchive archive(out);
		serialize(&archive, "");
	}
	void readFields(EDataInput* in) THROWS(EIOException) {
		EBinaryInputArchive archive(in);
		deserialize(&archive, "");
	}
	virtual int compareTo(EObject* peer_) THROWS(EClassCastException) {
		throw EUnsupportedOperationException(__FILE__, __LINE__,
				"comparing CreateRequest is unimplemented");
	}
	virtual boolean equals(EObject* peer_) {
		CreateRequest* peer = dynamic_cast<CreateRequest*>(peer_);
		if (!peer) {
			return false;
		}
		if (peer_ == this) {
			return true;
		}
		boolean ret = false;
		ret = path.equals(&peer->path);
		if (!ret)
			return ret;
		ret = bufEquals(data.get(), peer->data.get());
		if (!ret)
			return ret;
		ret = acl->equals(peer->acl.get());
		if (!ret)
			return ret;
		ret = (flags == peer->flags);
		if (!ret)
			return ret;
		return ret;
	}
	virtual int hashCode() {
		int result = 17;
		int ret;
		ret = path.hashCode();
		result = 37 * result + ret;
		ret = EArrays::toString(data.get()).hashCode();
		result = 37 * result + ret;
		ret = acl.hashCode();
		result = 37 * result + ret;
		ret = (int) flags;
		result = 37 * result + ret;
		return result;
	}
	static EString signature() {
		return "LCreateRequest(sB[LACL(iLId(ss))]i)";
	}
};

} /* namespace ezk */
} /* namespace efc */
#endif /* CreateRequest_HH_ */
