// File generated by hadoop record compiler. Do not edit.

#ifndef MultiHeader_HH_
#define MultiHeader_HH_

#include "Efc.hh"
#include "../../jute/inc/ERecord.hh"
#include "../../jute/inc/EBinaryInputArchive.hh"
#include "../../jute/inc/EBinaryOutputArchive.hh"
#include "../../jute/inc/ECsvOutputArchive.hh"

namespace efc {
namespace ezk {

class MultiHeader: public ERecord {
public:
	int type;
	boolean done;
	int err;

	MultiHeader() {
	}
	MultiHeader(int type, boolean done, int err) {
		this->type = type;
		this->done = done;
		this->err = err;
	}
	int getType() {
		return type;
	}
	void setType(int m_) {
		type = m_;
	}
	boolean getDone() {
		return done;
	}
	void setDone(boolean m_) {
		done = m_;
	}
	int getErr() {
		return err;
	}
	void setErr(int m_) {
		err = m_;
	}
	virtual void serialize(EOutputArchive* a_, const char* tag)
			THROWS(EIOException) {
		a_->startRecord(this, tag);
		a_->writeInt(type, "type");
		a_->writeBool(done, "done");
		a_->writeInt(err, "err");
		a_->endRecord(this, tag);
	}
	virtual void deserialize(EInputArchive* a_, const char* tag)
			THROWS(EIOException) {
		a_->startRecord(tag);
		type = a_->readInt("type");
		done = a_->readBool("done");
		err = a_->readInt("err");
		a_->endRecord(tag);
	}
	virtual EString toString() {
		try {
			EByteArrayOutputStream s;
			ECsvOutputArchive a_(&s);
			a_.startRecord(this, "");
			a_.writeInt(type, "type");
			a_.writeBool(done, "done");
			a_.writeInt(err, "err");
			a_.endRecord(this, "");
			s.write('\0');
			return (char*) s.data();
		} catch (EThrowable& ex) {
			ex.printStackTrace();
		}
		return "ERROR";
	}
	void write(EDataOutput* out) THROWS(EIOException) {
		EBinaryOutputArchive archive(out);
		serialize(&archive, "");
	}
	void readFields(EDataInput* in) THROWS(EIOException) {
		EBinaryInputArchive archive(in);
		deserialize(&archive, "");
	}
	virtual int compareTo(EObject* peer_) THROWS(EClassCastException) {
		MultiHeader* peer = dynamic_cast<MultiHeader*>(peer_);
		if (!peer) {
			throw EClassCastException(__FILE__, __LINE__,
					"Comparing different types of records.");
		}
		int ret = 0;
		ret = (type == peer->type) ? 0 : ((type < peer->type) ? -1 : 1);
		if (ret != 0)
			return ret;
		ret = (done == peer->done) ? 0 : (done ? 1 : -1);
		if (ret != 0)
			return ret;
		ret = (err == peer->err) ? 0 : ((err < peer->err) ? -1 : 1);
		if (ret != 0)
			return ret;
		return ret;
	}
	virtual boolean equals(EObject* peer_) {
		MultiHeader* peer = dynamic_cast<MultiHeader*>(peer_);
		if (!peer) {
			return false;
		}
		if (peer_ == this) {
			return true;
		}
		boolean ret = false;
		ret = (type == peer->type);
		if (!ret)
			return ret;
		ret = (done == peer->done);
		if (!ret)
			return ret;
		ret = (err == peer->err);
		if (!ret)
			return ret;
		return ret;
	}
	virtual int hashCode() {
		int result = 17;
		int ret;
		ret = (int) type;
		result = 37 * result + ret;
		ret = (done) ? 0 : 1;
		result = 37 * result + ret;
		ret = (int) err;
		result = 37 * result + ret;
		return result;
	}
	static EString signature() {
		return "LMultiHeader(izi)";
	}
};

} /* namespace ezk */
} /* namespace efc */
#endif /* MultiHeader_HH_ */
