// File generated by hadoop record compiler. Do not edit.

#ifndef ACL_HH_
#define ACL_HH_

#include "Efc.hh"
#include "../../jute/inc/ERecord.hh"
#include "./Id.hh"

namespace efc {
namespace ezk {

class ACL : public ERecord {
public:
	int perms;
	sp<Id> id;

	ACL() {
	}
	ACL(int perms, sp<Id> id) {
		this->perms = perms;
		this->id = id;
	}
	int getPerms() {
		return perms;
	}
	void setPerms(int m_) {
		perms = m_;
	}
	sp<Id> getId() {
		return id;
	}
	void setId(sp<Id> m_) {
		id = m_;
	}
	virtual void serialize(EOutputArchive* a_, const char* tag) THROWS(EIOException) {
		a_->startRecord(this, tag);
		a_->writeInt(perms, "perms");
		a_->writeRecord(id.get(), "id");
		a_->endRecord(this, tag);
	}
	virtual void deserialize(EInputArchive* a_, const char* tag) THROWS(EIOException) {
		a_->startRecord(tag);
		perms = a_->readInt("perms");
        id= new Id(); //???
		a_->readRecord(id.get(), "id");
		a_->endRecord(tag);
	}
	virtual EString toString() {
		try {
			EByteArrayOutputStream s;
			ECsvOutputArchive a_(&s);
			a_.startRecord(this, "");
			a_.writeInt(perms, "perms");
			a_.writeRecord(id.get(), "id");
			a_.endRecord(this, "");
			s.write('\0');
			return (char*)s.data();
		} catch (EThrowable& ex) {
			ex.printStackTrace();
		}
		return "ERROR";
	}
	void write(EDataOutput* out) THROWS(EIOException) {
		EBinaryOutputArchive archive(out);
		serialize(&archive, "");
	}
	void readFields(EDataInput* in) THROWS(EIOException) {
		EBinaryInputArchive archive(in);
		deserialize(&archive, "");
	}
	virtual int compareTo(EObject* peer_) THROWS(EClassCastException) {
		ACL* peer = dynamic_cast<ACL*>(peer_);
		if (!peer) {
			throw EClassCastException(__FILE__, __LINE__,
					"Comparing different types of records.");
		}
		int ret = 0;
		ret = (perms == peer->perms) ? 0 : ((perms < peer->perms) ? -1 : 1);
		if (ret != 0)
			return ret;
		ret = id->compareTo(peer->id.get());
		if (ret != 0)
			return ret;
		return ret;
	}
	virtual boolean equals(EObject* peer_) {
		ACL* peer = dynamic_cast<ACL*>(peer_);
		if (!peer) {
			return false;
		}
		if (peer_ == this) {
			return true;
		}
		boolean ret = false;
		ret = (perms == peer->perms);
		if (!ret)
			return ret;
		ret = id->equals(peer->id.get());
		if (!ret)
			return ret;
		return ret;
	}
	virtual int hashCode() {
		int result = 17;
		int ret;
		ret = (int) perms;
		result = 37 * result + ret;
		ret = id->hashCode();
		result = 37 * result + ret;
		return result;
	}
	static EString signature() {
		return "LACL(iLId(ss))";
	}
};

} /* namespace ezk */
} /* namespace efc */
#endif /* ACL_HH_ */
