<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_282) on Fri Feb 25 08:50:53 UTC 2022 -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>EphemeralType (Apache ZooKeeper - Server 3.8.0 API)</title>
<meta name="date" content="2022-02-25">
<link rel="stylesheet" type="text/css" href="../../../../stylesheet.css" title="Style">
<script type="text/javascript" src="../../../../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="EphemeralType (Apache ZooKeeper - Server 3.8.0 API)";
        }
    }
    catch(err) {
    }
//-->
var methods = {"i0":9,"i1":9,"i2":10,"i3":10,"i4":10,"i5":9,"i6":9,"i7":9,"i8":9};
var tabs = {65535:["t0","All Methods"],1:["t1","Static Methods"],2:["t2","Instance Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../../overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/EphemeralType.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../../index-all.html">Index</a></li>
<li><a href="../../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../../org/apache/zookeeper/server/DumbWatcher.html" title="class in org.apache.zookeeper.server"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li><a href="../../../../org/apache/zookeeper/server/EphemeralTypeEmulate353.html" title="enum in org.apache.zookeeper.server"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../../index.html?org/apache/zookeeper/server/EphemeralType.html" target="_top">Frames</a></li>
<li><a href="EphemeralType.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li><a href="#enum.constant.summary">Enum Constants</a>&nbsp;|&nbsp;</li>
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li><a href="#enum.constant.detail">Enum Constants</a>&nbsp;|&nbsp;</li>
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">org.apache.zookeeper.server</div>
<h2 title="Enum EphemeralType" class="title">Enum EphemeralType</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">java.lang.Object</a></li>
<li>
<ul class="inheritance">
<li><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true" title="class or interface in java.lang">java.lang.Enum</a>&lt;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>&gt;</li>
<li>
<ul class="inheritance">
<li>org.apache.zookeeper.server.EphemeralType</li>
</ul>
</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<dl>
<dt>All Implemented Interfaces:</dt>
<dd><a href="https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html?is-external=true" title="class or interface in java.io">Serializable</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html?is-external=true" title="class or interface in java.lang">Comparable</a>&lt;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>&gt;</dd>
</dl>
<hr>
<br>
<pre>public enum <span class="typeNameLabel">EphemeralType</span>
extends <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true" title="class or interface in java.lang">Enum</a>&lt;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>&gt;</pre>
<div class="block"><p>
 Abstraction that interprets the <code>ephemeralOwner</code> field of a ZNode. Originally,
 the ephemeralOwner noted that a ZNode is ephemeral and which session created the node.
 Through an optional system property (<code>zookeeper.extendedTypesEnabled</code>) "extended"
 features such as TTL Nodes can be enabled. Special bits of the ephemeralOwner are used to
 denote which feature is enabled and the remaining bits of the ephemeralOwner are feature
 specific.
 </p>
 <p>
 <p>
 When the system property <code>zookeeper.extendedTypesEnabled</code> is true, extended types
 are enabled. An extended ephemeralOwner is defined as an ephemeralOwner whose high 8 bits are
 set (<code>0xff00000000000000L</code>). The two bytes that follow the high 8 bits are
 used to denote which extended feature the ephemeralOwner represents. The remaining 5 bytes are
 used by the feature for whatever purpose is needed
 </p>
 <p>
 <p>
 Currently, the only extended feature is TTL Nodes. It is denoted by the extended feature value of 0.
 i.e. for TTL Nodes, the ephemeralOwner has the high byte set to 0xff and the next 2 bytes are 0 followed
 by 5 bytes that represent the TTL value in milliseconds. So, an ephemeralOwner with a TTL value of 1
 millisecond is: <code>0xff00000000000001</code>.
 </p>
 <p>
 <p>
 To add new extended features: a) Add a new name to the enum, b) define a constant EXTENDED_BIT_xxxx that's next
 in line (after TTLs, that would be <code>0x0001</code>), c) add a mapping to the extendedFeatureMap via the static
 initializer
 </p>
 <p>
 <p>
 NOTE: "Container" nodes technically are extended types but as it was implemented before this feature they are
 denoted specially. An ephemeral owner with only the high bit set (<code>0x8000000000000000L</code>) is by definition
 a container node (irrespective of whether or not extended types are enabled).
 </p></div>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- =========== ENUM CONSTANT SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="enum.constant.summary">
<!--   -->
</a>
<h3>Enum Constant Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Enum Constant Summary table, listing enum constants, and an explanation">
<caption><span>Enum Constants</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col">Enum Constant and Description</th>
</tr>
<tr class="altColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#CONTAINER">CONTAINER</a></span></code>
<div class="block">Container node</div>
</td>
</tr>
<tr class="rowColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#NORMAL">NORMAL</a></span></code>
<div class="block">Standard, pre-3.5.x EPHEMERAL</div>
</td>
</tr>
<tr class="altColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#TTL">TTL</a></span></code>
<div class="block">TTL node</div>
</td>
</tr>
<tr class="rowColor">
<td class="colOne"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#VOID">VOID</a></span></code>
<div class="block">Not ephemeral</div>
</td>
</tr>
</table>
</li>
</ul>
<!-- =========== FIELD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.summary">
<!--   -->
</a>
<h3>Field Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Field Summary table, listing fields, and an explanation">
<caption><span>Fields</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Field and Description</th>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static long</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#CONTAINER_EPHEMERAL_OWNER">CONTAINER_EPHEMERAL_OWNER</a></span></code>&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static long</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#MAX_EXTENDED_SERVER_ID">MAX_EXTENDED_SERVER_ID</a></span></code>&nbsp;</td>
</tr>
</table>
</li>
</ul>
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t1" class="tableTab"><span><a href="javascript:show(1);">Static Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t2" class="tableTab"><span><a href="javascript:show(2);">Instance Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tr id="i0" class="altColor">
<td class="colFirst"><code>static boolean</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#extendedEphemeralTypesEnabled--">extendedEphemeralTypesEnabled</a></span>()</code>
<div class="block">Return true if extended ephemeral types are enabled</div>
</td>
</tr>
<tr id="i1" class="rowColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#get-long-">get</a></span>(long&nbsp;ephemeralOwner)</code>
<div class="block">Convert a ZNode ephemeral owner to an ephemeral type.</div>
</td>
</tr>
<tr id="i2" class="altColor">
<td class="colFirst"><code>long</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#getValue-long-">getValue</a></span>(long&nbsp;ephemeralOwner)</code>
<div class="block">For types that support it, return the extended value from an extended ephemeral owner</div>
</td>
</tr>
<tr id="i3" class="rowColor">
<td class="colFirst"><code>long</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#maxValue--">maxValue</a></span>()</code>
<div class="block">For types that support it, the maximum extended value</div>
</td>
</tr>
<tr id="i4" class="altColor">
<td class="colFirst"><code>long</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#toEphemeralOwner-long-">toEphemeralOwner</a></span>(long&nbsp;value)</code>
<div class="block">For types that support it, convert a value to an extended ephemeral owner</div>
</td>
</tr>
<tr id="i5" class="rowColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#validateServerId-long-">validateServerId</a></span>(long&nbsp;serverId)</code>
<div class="block">Make sure the given server ID is compatible with the current extended ephemeral setting</div>
</td>
</tr>
<tr id="i6" class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#validateTTL-org.apache.zookeeper.CreateMode-long-">validateTTL</a></span>(<a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;mode,
           long&nbsp;ttl)</code>
<div class="block">Utility to validate a create mode and a ttl</div>
</td>
</tr>
<tr id="i7" class="rowColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a></code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#valueOf-java.lang.String-">valueOf</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;name)</code>
<div class="block">Returns the enum constant of this type with the specified name.</div>
</td>
</tr>
<tr id="i8" class="altColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>[]</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#values--">values</a></span>()</code>
<div class="block">Returns an array containing the constants of this enum type, in
the order they are declared.</div>
</td>
</tr>
</table>
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.java.lang.Enum">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true" title="class or interface in java.lang">Enum</a></h3>
<code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#clone--" title="class or interface in java.lang">clone</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#compareTo-E-" title="class or interface in java.lang">compareTo</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#equals-java.lang.Object-" title="class or interface in java.lang">equals</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#finalize--" title="class or interface in java.lang">finalize</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#getDeclaringClass--" title="class or interface in java.lang">getDeclaringClass</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#hashCode--" title="class or interface in java.lang">hashCode</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#name--" title="class or interface in java.lang">name</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#ordinal--" title="class or interface in java.lang">ordinal</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#toString--" title="class or interface in java.lang">toString</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html?is-external=true#valueOf-java.lang.Class-java.lang.String-" title="class or interface in java.lang">valueOf</a></code></li>
</ul>
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.java.lang.Object">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;java.lang.<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</a></h3>
<code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#getClass--" title="class or interface in java.lang">getClass</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#notify--" title="class or interface in java.lang">notify</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#notifyAll--" title="class or interface in java.lang">notifyAll</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait--" title="class or interface in java.lang">wait</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait-long-" title="class or interface in java.lang">wait</a>, <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true#wait-long-int-" title="class or interface in java.lang">wait</a></code></li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ============ ENUM CONSTANT DETAIL =========== -->
<ul class="blockList">
<li class="blockList"><a name="enum.constant.detail">
<!--   -->
</a>
<h3>Enum Constant Detail</h3>
<a name="VOID">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>VOID</h4>
<pre>public static final&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a> VOID</pre>
<div class="block">Not ephemeral</div>
</li>
</ul>
<a name="NORMAL">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>NORMAL</h4>
<pre>public static final&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a> NORMAL</pre>
<div class="block">Standard, pre-3.5.x EPHEMERAL</div>
</li>
</ul>
<a name="CONTAINER">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>CONTAINER</h4>
<pre>public static final&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a> CONTAINER</pre>
<div class="block">Container node</div>
</li>
</ul>
<a name="TTL">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>TTL</h4>
<pre>public static final&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a> TTL</pre>
<div class="block">TTL node</div>
</li>
</ul>
</li>
</ul>
<!-- ============ FIELD DETAIL =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.detail">
<!--   -->
</a>
<h3>Field Detail</h3>
<a name="CONTAINER_EPHEMERAL_OWNER">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>CONTAINER_EPHEMERAL_OWNER</h4>
<pre>public static final&nbsp;long CONTAINER_EPHEMERAL_OWNER</pre>
<dl>
<dt><span class="seeLabel">See Also:</span></dt>
<dd><a href="../../../../constant-values.html#org.apache.zookeeper.server.EphemeralType.CONTAINER_EPHEMERAL_OWNER">Constant Field Values</a></dd>
</dl>
</li>
</ul>
<a name="MAX_EXTENDED_SERVER_ID">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>MAX_EXTENDED_SERVER_ID</h4>
<pre>public static final&nbsp;long MAX_EXTENDED_SERVER_ID</pre>
<dl>
<dt><span class="seeLabel">See Also:</span></dt>
<dd><a href="../../../../constant-values.html#org.apache.zookeeper.server.EphemeralType.MAX_EXTENDED_SERVER_ID">Constant Field Values</a></dd>
</dl>
</li>
</ul>
</li>
</ul>
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a name="values--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>values</h4>
<pre>public static&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>[]&nbsp;values()</pre>
<div class="block">Returns an array containing the constants of this enum type, in
the order they are declared.  This method may be used to iterate
over the constants as follows:
<pre>
for (EphemeralType c : EphemeralType.values())
&nbsp;   System.out.println(c);
</pre></div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>an array containing the constants of this enum type, in the order they are declared</dd>
</dl>
</li>
</ul>
<a name="valueOf-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>valueOf</h4>
<pre>public static&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>&nbsp;valueOf(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;name)</pre>
<div class="block">Returns the enum constant of this type with the specified name.
The string must match <i>exactly</i> an identifier used to declare an
enum constant in this type.  (Extraneous whitespace characters are 
not permitted.)</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>name</code> - the name of the enum constant to be returned.</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>the enum constant with the specified name</dd>
<dt><span class="throwsLabel">Throws:</span></dt>
<dd><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/IllegalArgumentException.html?is-external=true" title="class or interface in java.lang">IllegalArgumentException</a></code> - if this enum type has no constant with the specified name</dd>
<dd><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/NullPointerException.html?is-external=true" title="class or interface in java.lang">NullPointerException</a></code> - if the argument is null</dd>
</dl>
</li>
</ul>
<a name="maxValue--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>maxValue</h4>
<pre>public&nbsp;long&nbsp;maxValue()</pre>
<div class="block">For types that support it, the maximum extended value</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>0 or max</dd>
</dl>
</li>
</ul>
<a name="toEphemeralOwner-long-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>toEphemeralOwner</h4>
<pre>public&nbsp;long&nbsp;toEphemeralOwner(long&nbsp;value)</pre>
<div class="block">For types that support it, convert a value to an extended ephemeral owner</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>0 or extended ephemeral owner</dd>
</dl>
</li>
</ul>
<a name="getValue-long-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getValue</h4>
<pre>public&nbsp;long&nbsp;getValue(long&nbsp;ephemeralOwner)</pre>
<div class="block">For types that support it, return the extended value from an extended ephemeral owner</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>0 or extended value</dd>
</dl>
</li>
</ul>
<a name="extendedEphemeralTypesEnabled--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>extendedEphemeralTypesEnabled</h4>
<pre>public static&nbsp;boolean&nbsp;extendedEphemeralTypesEnabled()</pre>
<div class="block">Return true if extended ephemeral types are enabled</div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>true/false</dd>
</dl>
</li>
</ul>
<a name="get-long-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>get</h4>
<pre>public static&nbsp;<a href="../../../../org/apache/zookeeper/server/EphemeralType.html" title="enum in org.apache.zookeeper.server">EphemeralType</a>&nbsp;get(long&nbsp;ephemeralOwner)</pre>
<div class="block">Convert a ZNode ephemeral owner to an ephemeral type. If extended types are not
 enabled, VOID or NORMAL is always returned</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>ephemeralOwner</code> - the ZNode's ephemeral owner</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>type</dd>
</dl>
</li>
</ul>
<a name="validateServerId-long-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>validateServerId</h4>
<pre>public static&nbsp;void&nbsp;validateServerId(long&nbsp;serverId)</pre>
<div class="block">Make sure the given server ID is compatible with the current extended ephemeral setting</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>serverId</code> - Server ID</dd>
<dt><span class="throwsLabel">Throws:</span></dt>
<dd><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/RuntimeException.html?is-external=true" title="class or interface in java.lang">RuntimeException</a></code> - extendedTypesEnabled is true but Server ID is too large</dd>
</dl>
</li>
</ul>
<a name="validateTTL-org.apache.zookeeper.CreateMode-long-">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>validateTTL</h4>
<pre>public static&nbsp;void&nbsp;validateTTL(<a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;mode,
                               long&nbsp;ttl)</pre>
<div class="block">Utility to validate a create mode and a ttl</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>mode</code> - create mode</dd>
<dd><code>ttl</code> - ttl</dd>
<dt><span class="throwsLabel">Throws:</span></dt>
<dd><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/IllegalArgumentException.html?is-external=true" title="class or interface in java.lang">IllegalArgumentException</a></code> - if the ttl is not valid for the mode</dd>
</dl>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../../overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="class-use/EphemeralType.html">Use</a></li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../../index-all.html">Index</a></li>
<li><a href="../../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../../org/apache/zookeeper/server/DumbWatcher.html" title="class in org.apache.zookeeper.server"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li><a href="../../../../org/apache/zookeeper/server/EphemeralTypeEmulate353.html" title="enum in org.apache.zookeeper.server"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="../../../../index.html?org/apache/zookeeper/server/EphemeralType.html" target="_top">Frames</a></li>
<li><a href="EphemeralType.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li><a href="#enum.constant.summary">Enum Constants</a>&nbsp;|&nbsp;</li>
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li><a href="#enum.constant.detail">Enum Constants</a>&nbsp;|&nbsp;</li>
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
<p class="legalCopy"><small>Copyright &#169; 2008&#x2013;2022 <a href="https://www.apache.org/">The Apache Software Foundation</a>. All rights reserved.</small></p>
</body>
</html>
