/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.jute.compiler;

import java.util.ArrayList;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;

/**
 * C++ Code generator front-end for Hadoop record I/O.
 *
 * @author Milind Bhandarkar
 */
class CGenerator {
    private String mFullName;
    private String mName;
    private ArrayList mInclFiles;
    private ArrayList mRecList;
    
    /** Creates a new instance of CppGenerator
     *
     * @param name possibly full pathname to the file
     * @param ilist included files (as JFile)
     * @param rlist List of records defined within this file
     */
    CGenerator(String name, ArrayList ilist, ArrayList rlist) {
        mFullName = name;
        mName = (new File(name)).getName();
        mInclFiles = ilist;
        mRecList = rlist;
    }
    
    /**
     * Generate C++ code. This method only creates the requested file(s)
     * and spits-out file-level elements (such as include statements etc.)
     * record-level code is generated by JRecord.
     */
    void genCode() throws IOException {
        FileWriter c = new FileWriter(mName+".c");
        FileWriter h = new FileWriter(mName+".h");
        h.write("#ifndef __"+mName.toUpperCase().replace('.','_')+"__\n");
        h.write("#define __"+mName.toUpperCase().replace('.','_')+"__\n");
        
        h.write("#include \"recordio.h\"\n");
        for (Iterator i = mInclFiles.iterator(); i.hasNext();) {
            JFile f = (JFile) i.next();
            h.write("#include \""+f.getName()+".h\"\n");
        }
        // required for compilation from C++
        h.write("\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

        c.write("#include <stdlib.h>\n"); // need it for calloc() & free()
        c.write("#include \""+mName+".h\"\n\n");
        
        for (Iterator i = mRecList.iterator(); i.hasNext();) {
            JRecord jr = (JRecord) i.next();
            jr.genCCode(h, c);
        }
        
        h.write("\n#ifdef __cplusplus\n}\n#endif\n\n");
        h.write("#endif //"+mName.toUpperCase().replace('.','_')+"__\n");
        
        h.close();
        c.close();
    }
}
