/*
 * This file was automatically generated by EvoSuite
 * Wed May 13 14:33:50 GMT 2026
 */

package org.apache.zookeeper.server;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PipedOutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.jute.BinaryInputArchive;
import org.apache.jute.BinaryOutputArchive;
import org.apache.jute.InputArchive;
import org.apache.jute.Record;
import org.apache.jute.ToStringOutputArchive;
import org.apache.zookeeper.DigestWatcher;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.data.Stat;
import org.apache.zookeeper.data.StatPersisted;
import org.apache.zookeeper.server.DataNode;
import org.apache.zookeeper.server.DataTree;
import org.apache.zookeeper.server.DigestCalculator;
import org.apache.zookeeper.server.DumbWatcher;
import org.apache.zookeeper.server.ZKDatabase;
import org.apache.zookeeper.server.persistence.FileTxnSnapLog;
import org.apache.zookeeper.txn.CloseSessionTxn;
import org.apache.zookeeper.txn.TxnDigest;
import org.apache.zookeeper.txn.TxnHeader;

@SuppressWarnings("deprecation")
public class DataTree_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try {
        dataTree0.reportDigestMismatch((-1884L));
        fail("Expecting exception: NoClassDefFoundError or ExceptionInInitializerError");

      } catch(NoClassDefFoundError | ExceptionInInitializerError e) {
         //
         // Could not initialize class org.apache.zookeeper.server.ServerMetrics
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try {
        dataTree0.deserialize((InputArchive) null, "<iQtS3K.<");
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.ReferenceCountedACLCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StatPersisted statPersisted0 = new StatPersisted(1663L, (-3245L), 788L, 1296L, 128, 128, (byte) (-42), 0L, 0L);
      DataTree.copyStatPersisted(statPersisted0, statPersisted0);
      assertEquals((-3245L), statPersisted0.getMzxid());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try {
        dataTree0.compareSnapshotDigests((-1618L));
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DumbWatcher dumbWatcher0 = new DumbWatcher(1113L);
      // Undeclared exception!
      try {
        dataTree0.addWatch("#/[{fQ$", dumbWatcher0, 1294);
        fail("Expecting exception: IllegalArgumentException");

      } catch(IllegalArgumentException e) {
         //
         // Unsupported mode: 1294
         //
         verifyException("org.apache.zookeeper.server.watch.WatcherMode", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      // Undeclared exception!
      try {
        dataTree0.deserializeLastProcessedZxid((InputArchive) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      File tmpFile0 = File.createTempFile("evosuite", ".tmp");
      tmpFile0.deleteOnExit();
      PrintStream printStream0 = new PrintStream(tmpFile0);
      ToStringOutputArchive toStringOutputArchive0 = new ToStringOutputArchive(printStream0);
      boolean boolean0 = dataTree0.serializeLastProcessedZxid(toStringOutputArchive0);
      assertEquals(1L, toStringOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (-479), (-1027));
      BinaryInputArchive binaryInputArchive0 = BinaryInputArchive.getArchive(byteArrayInputStream0);
      dataTree0.deserializeZxidDigest(binaryInputArchive0, (byte)10);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      TxnHeader txnHeader0 = new TxnHeader(2, 2565, 2611L, 500, (-1747));
      zKDatabase0.processTxn(txnHeader0, txnHeader0, (TxnDigest) null);
      assertEquals(2611L, zKDatabase0.getDataTreeLastProcessedZxid());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.PersistentRecursive;
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dataTree0.removeWatch("-fFSnt98L!L", watcher_WatcherType0, dumbWatcher0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Persistent;
      boolean boolean0 = dataTree0.removeWatch("true", watcher_WatcherType0, (Watcher) null);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.PersistentRecursive;
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dataTree0.containsWatcher("LF2+:", watcher_WatcherType0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try {
        dataTree0.setCversionPzxid(">W?O`,lf4/XV{5", 142, 626);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode for >W?O`,lf4/XV{5
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.dataTree;
      DumbWatcher dumbWatcher0 = new DumbWatcher(500);
      Vector<Locale.LanguageRange> vector0 = new Vector<Locale.LanguageRange>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector0, (Collection<String>) null, locale_FilteringMode0);
      dataTree0.setWatches(2499L, list0, list0, list0, list0, list0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getEphemerals();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      PrintWriter printWriter0 = new PrintWriter("P0=/");
      zKDatabase0.dumpEphemerals(printWriter0);
      assertEquals(0L, zKDatabase0.getminCommittedLog());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      File tmpFile0 = File.createTempFile("evosuite", ".tmp");
      tmpFile0.deleteOnExit();
      FileOutputStream fileOutputStream0 = new FileOutputStream(tmpFile0);
      ToStringOutputArchive toStringOutputArchive0 = new ToStringOutputArchive(fileOutputStream0);
      StringBuilder stringBuilder0 = new StringBuilder();
      dataTree0.serializeNode(toStringOutputArchive0, stringBuilder0);
      assertEquals("/zookeeper/quota/", stringBuilder0.toString());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.dataTree;
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      // Undeclared exception!
      try {
        dataTree0.killSession((-1392L), 0, set0, (List<String>) null);
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader();
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0, true);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, dataTree_ProcessTxnResult0.err);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.dataTree;
      TxnHeader txnHeader0 = new TxnHeader();
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0);
      CloseSessionTxn closeSessionTxn0 = new CloseSessionTxn();
      boolean boolean0 = dataTree_ProcessTxnResult0.equals(closeSessionTxn0);
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, dataTree_ProcessTxnResult0.err);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stat stat0 = new Stat(128, 128, 0L, 1024, 543, 128, 28, (-670L), 0, 28, 3422L);
      try {
        dataTree0.getACL("q_f0g5LE3", stat0);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      ArrayList<ACL> arrayList0 = new ArrayList<ACL>();
      try {
        dataTree0.setACL("h.M1Yy2=", arrayList0, 500);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      int int0 = dataTree0.getAllChildrenNumber("LF2+:");
      assertEquals(0, int0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Stat stat0 = new Stat();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      try {
        dataTree0.getChildren("//", stat0, dumbWatcher0);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.dataTree;
      DumbWatcher dumbWatcher0 = new DumbWatcher(500);
      try {
        dataTree0.statNode("jT,W", dumbWatcher0);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      Stat stat0 = new Stat(1277L, 1277L, (-1112L), (-604L), 728, 747, 4951, 4951, (-635), 4951, (-1112L));
      try {
        zKDatabase0.getData("?wJ$KMDi", stat0, (Watcher) null);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      String string0 = dataTree0.getMaxPrefixWithQuota("R>^s|Lo2lo6E");
      assertNull(string0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      byte[] byteArray0 = new byte[9];
      try {
        dataTree0.setData("EppB4je9Vklfq", byteArray0, (byte)38, 2516L, (-115L));
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      Vector<String> vector0 = new Vector<String>();
      // Undeclared exception!
      try {
        dataTree0.killSession(3442L, 3442L, set0, vector0);
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stack<ACL> stack0 = new Stack<ACL>();
      try {
        dataTree0.createNode("x?C/", (byte[]) null, (List<ACL>) stack0, (-3703L), (-38), (-1400L), 1629L, (Stat) null);
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.updateQuotaStat("fg@#K#2]!a9a>sV\"=", (-4833L), 635);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      boolean boolean0 = dataTree0.isSpecialPath("");
      assertFalse(boolean0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      int int0 = dataTree0.getEphemeralsCount();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(0, int0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getEphemerals(224L);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      File tmpFile0 = File.createTempFile("evosuite", ".tmp");
      tmpFile0.deleteOnExit();
      FileOutputStream fileOutputStream0 = new FileOutputStream(tmpFile0);
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream(fileOutputStream0);
      PrintStream printStream0 = new PrintStream(bufferedOutputStream0, false);
      ToStringOutputArchive toStringOutputArchive0 = new ToStringOutputArchive(printStream0);
      boolean boolean0 = dataTree0.serializeZxidDigest(toStringOutputArchive0);
      assertEquals(5L, toStringOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest(31L, (-35), 31L);
      int int0 = dataTree_ZxidDigest0.getDigestVersion();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(31L, dataTree_ZxidDigest0.getZxid());
      assertEquals((-35), int0);
      assertEquals(31L, dataTree_ZxidDigest0.getDigest());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest((-1467L), (-1466), (-1467L));
      long long0 = dataTree_ZxidDigest0.getDigest();
      assertEquals((-1467L), dataTree_ZxidDigest0.getZxid());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals((-1466), dataTree_ZxidDigest0.getDigestVersion());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals((-1467L), long0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Stat stat0 = new Stat(128, 128, 0L, 1024, 543, 128, 28, (-670L), 0, 28, 3422L);
      DataTree.copyStat(stat0, stat0);
      assertEquals(128, stat0.getCversion());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter(pipedOutputStream0);
      dataTree0.dumpWatchesSummary(printWriter0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getReferenceCountedAclCache();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getWatchesSummary();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.aclCacheSize();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      StatPersisted statPersisted0 = DataTree.createStat(1024);
      assertEquals(0L, statPersisted0.getCtime());
      assertEquals(0L, statPersisted0.getMzxid());
      assertEquals(0L, statPersisted0.getMtime());
      assertEquals(0L, statPersisted0.getCzxid());
      assertEquals(0L, statPersisted0.getEphemeralOwner());
      assertEquals(0L, statPersisted0.getPzxid());
      assertEquals(0, statPersisted0.getAversion());
      assertEquals(1024, statPersisted0.getVersion());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      byte[] byteArray0 = new byte[6];
      // Undeclared exception!
      try {
        dataTree0.createNode("0B)IV%Ocu>Y", byteArray0, (List<ACL>) null, (long) (byte) (-117), 2498, (-3806L), (-2932L));
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getWatchCount();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      PrintWriter printWriter0 = new PrintWriter(charArrayWriter0);
      dataTree0.dumpWatches(printWriter0, false);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  /* Commented out: relies on EvoSuite mock IO behavior (NativeMockedIO)
  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      FileOutputStream fileOutputStream0 = new FileOutputStream(File.createTempFile("evosuite", ".tmp"));
      BinaryOutputArchive binaryOutputArchive0 = BinaryOutputArchive.getArchive(fileOutputStream0);
      try {
        dataTree0.serialize(binaryOutputArchive0, "#JhF^Gr");
        fail("Expecting exception: IOException");

      } catch(IOException e) {
         //
         // Error in writing to file
         //
         verifyException("org.evosuite.runtime.mock.java.io.NativeMockedIO", e);
      }
  }
  */

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dataTree0.removeCnxn(dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getDigestLog();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.shutdownWatcher();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      long long0 = dataTree0.cachedApproximateDataSize();
      assertEquals(44L, long0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      TxnHeader txnHeader0 = new TxnHeader(2, 500, 1920L, 68, 128);
      StatPersisted statPersisted0 = DataTree.createStat(69L, 1629L, 1920L);
      TxnDigest txnDigest0 = new TxnDigest();
      zKDatabase0.processTxn(txnHeader0, statPersisted0, txnDigest0);
      assertEquals(1920L, zKDatabase0.getDataTreeLastProcessedZxid());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.dataTree;
      dataTree0.killSession(1131L, 2);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getTtls();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getWatchesByPath();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getLastProcessedZxidDigest();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      DataNode dataNode0 = new DataNode();
      dataTree0.getACL(dataNode0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getDigestFromLoadedSnapshot();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.addDigestWatcher((DigestWatcher) null);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Set<String> set0 = dataTree0.getContainers();
      Vector<Locale.LanguageRange> vector0 = new Vector<Locale.LanguageRange>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector0, (Collection<String>) set0, locale_FilteringMode0);
      dataTree0.killSession(594L, 594L, set0, list0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getWatches();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getSessions();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      File tmpFile0 = File.createTempFile("evodir", "");
      tmpFile0.delete();
      tmpFile0.mkdirs();
      tmpFile0.deleteOnExit();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(tmpFile0, tmpFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      dataTree0.getNodeCount();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }
}