/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 08:11:15 GMT 2026
 */

package org.apache.zookeeper.server;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.List;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.jute.BinaryInputArchive;
import org.apache.jute.BinaryOutputArchive;
import org.apache.jute.InputArchive;
import org.apache.jute.Record;
import org.apache.jute.ToStringOutputArchive;
import org.apache.zookeeper.DigestWatcher;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.data.Stat;
import org.apache.zookeeper.data.StatPersisted;
import org.apache.zookeeper.server.DataNode;
import org.apache.zookeeper.server.DataTree;
import org.apache.zookeeper.server.DigestCalculator;
import org.apache.zookeeper.server.DumbWatcher;
import org.apache.zookeeper.server.ZKDatabase;
import org.apache.zookeeper.server.persistence.FileTxnSnapLog;
import org.apache.zookeeper.txn.TxnDigest;
import org.apache.zookeeper.txn.TxnHeader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataTreeC4_ESTest extends DataTreeC4_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try { 
        dataTree0.reportDigestMismatch(2093L);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.zookeeper.server.ServerMetrics
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.dataTree;
      byte[] byteArray0 = new byte[6];
      StatPersisted statPersisted0 = DataTree.createStat((byte)70, (-1597L), (byte)105);
      DataNode dataNode0 = new DataNode(byteArray0, (Long) 0L, statPersisted0);
      // Undeclared exception!
      try { 
        dataTree0.getACL(dataNode0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to fetch acls for 0
         //
         verifyException("org.apache.zookeeper.server.ReferenceCountedACLCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[8];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      BinaryInputArchive binaryInputArchive0 = BinaryInputArchive.getArchive(byteArrayInputStream0);
      boolean boolean0 = dataTree0.deserializeLastProcessedZxid(binaryInputArchive0);
      assertEquals(0, byteArrayInputStream0.available());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      byte[] byteArray0 = new byte[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      BinaryInputArchive binaryInputArchive0 = BinaryInputArchive.getArchive(byteArrayInputStream0);
      try { 
        dataTree0.deserialize(binaryInputArchive0, "zookeeper.commitLogCount");
        fail("Expecting exception: EOFException");
      
      } catch(EOFException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.DataInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try { 
        dataTree0.compareSnapshotDigests(4020L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try { 
        dataTree0.addWatch("lz0 ~@", (Watcher) null, (-3641));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported mode: -3641
         //
         verifyException("org.apache.zookeeper.server.watch.WatcherMode", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader();
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0, (TxnDigest) null);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(0, dataTree_ProcessTxnResult0.err);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      BinaryInputArchive binaryInputArchive0 = BinaryInputArchive.getArchive(byteArrayInputStream0);
      boolean boolean0 = dataTree0.deserializeLastProcessedZxid(binaryInputArchive0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertFalse(boolean0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      BinaryOutputArchive binaryOutputArchive0 = BinaryOutputArchive.getArchive(byteArrayOutputStream0);
      boolean boolean0 = dataTree0.serializeLastProcessedZxid(binaryOutputArchive0);
      assertEquals(8L, binaryOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try { 
        dataTree0.deserializeZxidDigest((InputArchive) null, 1538L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree$ZxidDigest", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader();
      dataTree0.processTxn(txnHeader0, (Record) txnHeader0, false);
      MockFile mockFile0 = new MockFile("C");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      ToStringOutputArchive toStringOutputArchive0 = new ToStringOutputArchive(mockFileOutputStream0);
      boolean boolean0 = dataTree0.serializeZxidDigest(toStringOutputArchive0);
      assertEquals(14L, toStringOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader(0L, 910, (-487L), 1024, 1024);
      TxnDigest txnDigest0 = new TxnDigest();
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0, txnDigest0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, dataTree_ProcessTxnResult0.err);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Persistent;
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = dataTree0.removeWatch("g4g>i])?", watcher_WatcherType0, dumbWatcher0);
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Any;
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = dataTree0.removeWatch("phuO", watcher_WatcherType0, dumbWatcher0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Any;
      DumbWatcher dumbWatcher0 = new DumbWatcher(667L);
      boolean boolean0 = dataTree0.containsWatcher("", watcher_WatcherType0, dumbWatcher0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.PersistentRecursive;
      dataTree0.containsWatcher("wayEP`$Qa", watcher_WatcherType0, (Watcher) null);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Data;
      DumbWatcher dumbWatcher0 = new DumbWatcher(0L);
      dataTree0.containsWatcher("0wxIvCq63!^?Cy", watcher_WatcherType0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Persistent;
      DumbWatcher dumbWatcher0 = new DumbWatcher(0L);
      dataTree0.containsWatcher("0wxIvCq63!^?Cy", watcher_WatcherType0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Children;
      dataTree0.containsWatcher("zookeeper.snapshot.trust.empty", watcher_WatcherType0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      try { 
        dataTree0.setCversionPzxid("Wn/", (-2505), (-281L));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode for Wn
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.setCversionPzxid("k5y8Df0g;0q9^?~", (-521), (-521));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode for k5y8Df0g;0q9^?~
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stack<String> stack0 = new Stack<String>();
      DumbWatcher dumbWatcher0 = new DumbWatcher(0L);
      stack0.add("&mD)],w*!uFiT");
      dataTree0.setWatches(1635L, stack0, stack0, stack0, stack0, stack0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getEphemerals();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("version-");
      dataTree0.dumpEphemerals(mockPrintWriter0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader(1024, (-209), 1155L, 3223L, (-209));
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) null, true);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, dataTree_ProcessTxnResult0.err);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader(128, 1024, 1024, 0L, 1024);
      TxnDigest txnDigest0 = new TxnDigest();
      dataTree0.processTxn(txnHeader0, (Record) txnHeader0, txnDigest0);
      assertEquals(1024L, dataTree0.lastProcessedZxid);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = new DataTree.ProcessTxnResult();
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      boolean boolean0 = dataTree_ProcessTxnResult0.equals(dataTree0);
      assertFalse(boolean0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.getACL("z7BBH(?I}6J)[njmi^", (Stat) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.setACL("q4&yS7e+", (List<ACL>) null, 3732);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      int int0 = dataTree0.getAllChildrenNumber("[.jdK");
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stat stat0 = new Stat();
      DumbWatcher dumbWatcher0 = new DumbWatcher(480L);
      try { 
        dataTree0.getChildren("?F", stat0, dumbWatcher0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DumbWatcher dumbWatcher0 = new DumbWatcher(68);
      try { 
        dataTree0.statNode("{-cF", dumbWatcher0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.statNode(">A%?_I<LG?1@G`1!8", (Watcher) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DumbWatcher dumbWatcher0 = new DumbWatcher(1024);
      try { 
        dataTree0.getData("l`L", (Stat) null, dumbWatcher0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[8];
      try { 
        dataTree0.setData("Unreasonable length = ", byteArray0, (-1899), (byte)78, 1259L);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      try { 
        dataTree0.deleteNode("UoGq31c/<R,Vjf`_", (-2609L));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.updateQuotaStat("", 725L, (-490));
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      boolean boolean0 = dataTree0.isSpecialPath("m'!O6OXmL/8DJ6NW");
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      int int0 = dataTree0.getEphemeralsCount();
      assertEquals(0, int0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getEphemerals(725L);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      MockFile mockFile0 = new MockFile("C");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      ToStringOutputArchive toStringOutputArchive0 = new ToStringOutputArchive(mockFileOutputStream0);
      boolean boolean0 = dataTree0.serializeZxidDigest(toStringOutputArchive0);
      assertEquals(5L, toStringOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest((-2043L), 1024, 852L);
      int int0 = dataTree_ZxidDigest0.getDigestVersion();
      assertEquals(1024, int0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(852L, dataTree_ZxidDigest0.getDigest());
      assertEquals((-2043L), dataTree_ZxidDigest0.getZxid());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MockFile mockFile0 = new MockFile("d?^Y|n7\"Q>73S", "=aSO@jEuctp`Te");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.dataTree;
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest();
      dataTree_ZxidDigest0.getZxid();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(2, dataTree_ZxidDigest0.getDigestVersion());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest();
      dataTree_ZxidDigest0.getDigest();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(2, dataTree_ZxidDigest0.getDigestVersion());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Stat stat0 = new Stat(68, 0L, (-490), 1024, (-2356), 68, 2074, 3000L, (-499), 1024, 560L);
      DataTree.copyStat(stat0, stat0);
      assertEquals(68L, stat0.getCzxid());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      StatPersisted statPersisted0 = new StatPersisted();
      DataTree.copyStatPersisted(statPersisted0, statPersisted0);
      assertEquals(0L, statPersisted0.getCtime());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("@k?h`r>6[W");
      dataTree0.dumpWatchesSummary(mockPrintWriter0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getReferenceCountedAclCache();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getWatchesSummary();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.aclCacheSize();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      StatPersisted statPersisted0 = DataTree.createStat((-3045));
      assertEquals(0L, statPersisted0.getMzxid());
      assertEquals(0L, statPersisted0.getPzxid());
      assertEquals(0, statPersisted0.getAversion());
      assertEquals(0L, statPersisted0.getCzxid());
      assertEquals(0L, statPersisted0.getCtime());
      assertEquals(0L, statPersisted0.getMtime());
      assertEquals(0L, statPersisted0.getEphemeralOwner());
      assertEquals((-3045), statPersisted0.getVersion());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[3];
      // Undeclared exception!
      try { 
        dataTree0.createNode("IsAHy", byteArray0, (List<ACL>) null, (long) 0, (int) (byte)23, (-2339L), (-2861L));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getWatchCount();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.dumpWatches((PrintWriter) null, false);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("/@Q'fDrt0", false);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockFileOutputStream0);
      BinaryOutputArchive binaryOutputArchive0 = new BinaryOutputArchive(objectOutputStream0);
      dataTree0.serialize(binaryOutputArchive0, "@}N");
      assertEquals(391L, binaryOutputArchive0.getDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dataTree0.removeCnxn(dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stack<ACL> stack0 = new Stack<ACL>();
      try { 
        dataTree0.createNode("x?C/", (byte[]) null, (List<ACL>) stack0, (-3703L), (-38), (-1400L), 1629L, (Stat) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getDigestLog();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.shutdownWatcher();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      MockFile mockFile0 = new MockFile("bPDk\" u*F_", "bPDk\" u*F_");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      long long0 = dataTree0.cachedApproximateDataSize();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, long0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.killSession((-1144L), 1477L);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Set<String> set0 = dataTree0.getTtls();
      Vector<String> vector0 = new Vector<String>();
      dataTree0.killSession(1125L, (-2467L), set0, vector0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getWatchesByPath();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getLastProcessedZxidDigest();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[8];
      dataTree0.setData("", byteArray0, (byte)99, 560L, (-1827L));
      assertEquals(52L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getDigestFromLoadedSnapshot();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      DigestWatcher digestWatcher0 = mock(DigestWatcher.class, new ViolatedAssumptionAnswer());
      dataTree0.addDigestWatcher(digestWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getContainers();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getWatches();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getSessions();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getNodeCount();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }
}
