/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 07:55:26 GMT 2026
 */

package org.apache.zookeeper.server;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.ObjectOutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.util.ArrayDeque;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.jute.BinaryInputArchive;
import org.apache.jute.BinaryOutputArchive;
import org.apache.jute.InputArchive;
import org.apache.jute.Record;
import org.apache.zookeeper.DigestWatcher;
import org.apache.zookeeper.MultiOperationRecord;
import org.apache.zookeeper.Op;
import org.apache.zookeeper.Watcher;
import org.apache.zookeeper.data.ACL;
import org.apache.zookeeper.data.Stat;
import org.apache.zookeeper.data.StatPersisted;
import org.apache.zookeeper.server.DataNode;
import org.apache.zookeeper.server.DataTree;
import org.apache.zookeeper.server.DigestCalculator;
import org.apache.zookeeper.server.DumbWatcher;
import org.apache.zookeeper.server.ZKDatabase;
import org.apache.zookeeper.server.persistence.FileTxnSnapLog;
import org.apache.zookeeper.txn.TxnDigest;
import org.apache.zookeeper.txn.TxnHeader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataTreeC2_ESTest extends DataTreeC2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      // Undeclared exception!
      try { 
        dataTree0.reportDigestMismatch(500);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.zookeeper.server.ServerMetrics
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      // Undeclared exception!
      try { 
        dataTree0.deserialize((InputArchive) null, " 6z-vfIza+X");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.ReferenceCountedACLCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Stat stat0 = new Stat((-3408), 3252L, 1522L, 588L, (-3408), (-4443), (-3408), 588L, (-4443), (-3408), (-2414L));
      DataTree.copyStat(stat0, stat0);
      assertEquals((-3408), stat0.getVersion());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      // Undeclared exception!
      try { 
        dataTree0.compareSnapshotDigests((-3532L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      DumbWatcher dumbWatcher0 = new DumbWatcher((-1114L));
      // Undeclared exception!
      try { 
        dataTree0.addWatch("vbtH8z%>f39F", dumbWatcher0, 6021);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported mode: 6021
         //
         verifyException("org.apache.zookeeper.server.watch.WatcherMode", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      StatPersisted statPersisted0 = new StatPersisted();
      TxnHeader txnHeader0 = new TxnHeader();
      boolean boolean0 = dataTree0.compareDigest(txnHeader0, statPersisted0, (TxnDigest) null);
      assertTrue(boolean0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      DataInputStream dataInputStream0 = new DataInputStream(byteArrayInputStream0);
      BinaryInputArchive binaryInputArchive0 = new BinaryInputArchive(dataInputStream0);
      boolean boolean0 = dataTree0.deserializeLastProcessedZxid(binaryInputArchive0);
      assertEquals(1, byteArrayInputStream0.available());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      BinaryOutputArchive binaryOutputArchive0 = BinaryOutputArchive.getArchive(byteArrayOutputStream0);
      boolean boolean0 = dataTree0.serializeLastProcessedZxid(binaryOutputArchive0);
      assertEquals(8L, binaryOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      // Undeclared exception!
      try { 
        dataTree0.deserializeZxidDigest((InputArchive) null, 44L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree$ZxidDigest", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.PersistentRecursive;
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = dataTree0.removeWatch("Y3g0&rYcxlb ", watcher_WatcherType0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Persistent;
      boolean boolean0 = dataTree0.removeWatch("ojSiB`HzNXI|tch", watcher_WatcherType0, (Watcher) null);
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Data;
      DumbWatcher dumbWatcher0 = new DumbWatcher(0L);
      boolean boolean0 = dataTree0.removeWatch("%", watcher_WatcherType0, dumbWatcher0);
      assertFalse(boolean0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Any;
      DumbWatcher dumbWatcher0 = new DumbWatcher((-1114L));
      boolean boolean0 = dataTree0.removeWatch("vbtH8z%>f39F", watcher_WatcherType0, dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Children;
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      boolean boolean0 = dataTree0.removeWatch((String) null, watcher_WatcherType0, dumbWatcher0);
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Any;
      boolean boolean0 = dataTree0.containsWatcher("A{a6", watcher_WatcherType0, (Watcher) null);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.PersistentRecursive;
      boolean boolean0 = dataTree0.containsWatcher("ojSiB`HzNXI|tch", watcher_WatcherType0, (Watcher) null);
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Data;
      boolean boolean0 = dataTree0.containsWatcher("ojSiB`HzNXI|tch", watcher_WatcherType0, (Watcher) null);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertFalse(boolean0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Watcher.WatcherType watcher_WatcherType0 = Watcher.WatcherType.Persistent;
      boolean boolean0 = dataTree0.containsWatcher("ojSiB`HzNXI|tch", watcher_WatcherType0, (Watcher) null);
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.setCversionPzxid("", 128, 252L);
      assertEquals(2449308958L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      try { 
        dataTree0.setCversionPzxid("s:9E>-", (-494), (-494));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode for s:9E>-
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.setCversionPzxid("", (-118), 2207L);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stack<String> stack0 = new Stack<String>();
      stack0.add("`ctl:");
      // Undeclared exception!
      try { 
        dataTree0.setWatches((-898L), stack0, stack0, stack0, stack0, stack0, (Watcher) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Stack<String> stack0 = new Stack<String>();
      dataTree0.setWatches(128, stack0, stack0, stack0, stack0, stack0, (Watcher) null);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getEphemerals();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MockFile mockFile0 = new MockFile("wbF{zRI~5L``niojYv");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("tt;njl");
      zKDatabase0.dumpEphemerals(mockPrintWriter0);
      assertEquals(0L, zKDatabase0.getTxnSize());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MockFile mockFile0 = new MockFile("z7d8.)U");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("zookeeper.snapshot.trust.empty");
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream(mockFileOutputStream0, 68);
      MockPrintStream mockPrintStream0 = new MockPrintStream(bufferedOutputStream0, false);
      DataOutputStream dataOutputStream0 = new DataOutputStream(mockPrintStream0);
      BinaryOutputArchive binaryOutputArchive0 = new BinaryOutputArchive(dataOutputStream0);
      StringBuilder stringBuilder0 = new StringBuilder();
      stringBuilder0.append(false);
      dataTree0.serializeNode(binaryOutputArchive0, stringBuilder0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      Stack<String> stack0 = new Stack<String>();
      Locale locale0 = Locale.US;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      dataTree0.killSession((-1497L), (-993L), set0, stack0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      TxnHeader txnHeader0 = new TxnHeader(5292L, 3462, 3782L, (-1396L), 1011);
      dataTree0.processTxn(txnHeader0, (Record) txnHeader0, false);
      assertEquals(3782L, dataTree0.lastProcessedZxid);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      TxnHeader txnHeader0 = new TxnHeader();
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0, true);
      assertEquals(0, dataTree_ProcessTxnResult0.err);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      TxnHeader txnHeader0 = new TxnHeader(500, 128, 0L, 68, 2);
      // Undeclared exception!
      try { 
        dataTree0.processTxn(txnHeader0, (Record) txnHeader0, false);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.zookeeper.txn.TxnHeader cannot be cast to org.apache.zookeeper.txn.DeleteTxn
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader();
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, dataTree_ProcessTxnResult0.err);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = new DataTree.ProcessTxnResult();
      ArrayDeque<Op> arrayDeque0 = new ArrayDeque<Op>();
      MultiOperationRecord multiOperationRecord0 = new MultiOperationRecord(arrayDeque0);
      boolean boolean0 = dataTree_ProcessTxnResult0.equals(multiOperationRecord0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MockFile mockFile0 = new MockFile("=,JpJlSCf_e", "=,JpJlSCf_e");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      Stat stat0 = new Stat(2747L, 0L, (byte)123, (-1060L), (-646), 1526, 1024, (-1060L), 1443, 66, 50L);
      try { 
        zKDatabase0.getACL(">", stat0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      try { 
        dataTree0.setACL("zookeeper.snapshot.trust.empty", (List<ACL>) null, (-1197));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      int int0 = dataTree0.getAllChildrenNumber("qCmzp ");
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DumbWatcher dumbWatcher0 = new DumbWatcher(1885L);
      try { 
        dataTree0.getChildren("NId-*a&^;P'}y:BF", (Stat) null, dumbWatcher0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      try { 
        zKDatabase0.statNode("MS", dumbWatcher0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      try { 
        dataTree0.statNode(";3%|", (Watcher) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.getData("9.R<+i#;xM<B", (Stat) null, (Watcher) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      Stat stat0 = new Stat();
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dataTree0.getData("", stat0, dumbWatcher0);
      assertEquals(1, stat0.getNumChildren());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MockFile mockFile0 = new MockFile("z7d8.)U");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      String string0 = dataTree0.getMaxPrefixWithQuota("");
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[2];
      try { 
        dataTree0.setData("}@H", byteArray0, (byte) (-46), 1464L, (-958L));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.deleteNode("/!yih}cq&u<*@c_;", 2128L);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      try { 
        dataTree0.deleteNode("/!yih}cq&u<*@c_;", 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.updateQuotaStat((String) null, 2207L, (-3224));
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      boolean boolean0 = dataTree0.isSpecialPath("Y3g0&rYcxlb ");
      assertFalse(boolean0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      int int0 = dataTree0.getEphemeralsCount();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getEphemerals(212L);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream(pipedInputStream0);
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream(pipedOutputStream0);
      BinaryOutputArchive binaryOutputArchive0 = BinaryOutputArchive.getArchive(bufferedOutputStream0);
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      boolean boolean0 = dataTree0.serializeZxidDigest(binaryOutputArchive0);
      assertEquals(20L, binaryOutputArchive0.getDataSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest();
      int int0 = dataTree_ZxidDigest0.getDigestVersion();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest((-2018L), (-1136), (-3964L));
      long long0 = dataTree_ZxidDigest0.getZxid();
      assertEquals((-1136), dataTree_ZxidDigest0.getDigestVersion());
      assertEquals((-3964L), dataTree_ZxidDigest0.getDigest());
      assertEquals((-2018L), long0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DataTree.ZxidDigest dataTree_ZxidDigest0 = dataTree0.new ZxidDigest(668L, 1005, 668L);
      long long0 = dataTree_ZxidDigest0.getDigest();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(1005, dataTree_ZxidDigest0.getDigestVersion());
      assertEquals(668L, long0);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(668L, dataTree_ZxidDigest0.getZxid());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      StatPersisted statPersisted0 = new StatPersisted();
      DataTree.copyStatPersisted(statPersisted0, statPersisted0);
      assertEquals(0, statPersisted0.getVersion());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      MockPrintStream mockPrintStream0 = new MockPrintStream("ZHr3CP/nE=;~5");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0, false);
      dataTree0.dumpWatchesSummary(mockPrintWriter0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getReferenceCountedAclCache();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.dataTree;
      dataTree0.getWatchesSummary();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.aclCacheSize();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MockFile mockFile0 = new MockFile("z7d8.)U");
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog(mockFile0, mockFile0);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      byte[] byteArray0 = new byte[3];
      Vector<ACL> vector0 = new Vector<ACL>();
      // Undeclared exception!
      try { 
        dataTree0.createNode("J\"5'%VC", byteArray0, (List<ACL>) vector0, 1015L, 2856, (-1441L), (long) 2);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      dataTree0.getWatchCount();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      MockPrintStream mockPrintStream0 = new MockPrintStream("zookeeper.kerberos.canonicalizeHostNames");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0);
      dataTree0.dumpWatches(mockPrintWriter0, true);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      MockFile mockFile0 = new MockFile(",9");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockPrintStream0);
      BinaryOutputArchive binaryOutputArchive0 = BinaryOutputArchive.getArchive(objectOutputStream0);
      dataTree0.serialize(binaryOutputArchive0, " 6c");
      assertEquals(391L, binaryOutputArchive0.getDataSize());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      dataTree0.removeCnxn(dumbWatcher0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      byte[] byteArray0 = new byte[0];
      try { 
        dataTree0.createNode("]{Es/zr]", byteArray0, (List<ACL>) null, 0L, (-874), (-337L), 203L, (Stat) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // KeeperErrorCode = NoNode
         //
         verifyException("org.apache.zookeeper.server.DataTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getDigestLog();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.shutdownWatcher();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      long long0 = dataTree0.cachedApproximateDataSize();
      assertEquals(44L, long0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.killSession(235L, 1140L);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      ZKDatabase zKDatabase0 = new ZKDatabase((FileTxnSnapLog) null);
      DataTree dataTree0 = zKDatabase0.getDataTree();
      dataTree0.getTtls();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getWatchesByPath();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getLastProcessedZxidDigest();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      byte[] byteArray0 = new byte[8];
      StatPersisted statPersisted0 = DataTree.createStat((int) (byte) (-41));
      DataNode dataNode0 = new DataNode(byteArray0, (Long) 0L, statPersisted0);
      // Undeclared exception!
      try { 
        dataTree0.getACL(dataNode0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Failed to fetch acls for 0
         //
         verifyException("org.apache.zookeeper.server.ReferenceCountedACLCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getDigestFromLoadedSnapshot();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.addDigestWatcher((DigestWatcher) null);
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getContainers();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      DigestCalculator digestCalculator0 = new DigestCalculator();
      DataTree dataTree0 = new DataTree(digestCalculator0);
      dataTree0.getWatches();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      TxnHeader txnHeader0 = new TxnHeader(1024, 23, (-1114L), 2210L, 68);
      TxnDigest txnDigest0 = new TxnDigest(23, (-1114L));
      DataTree.ProcessTxnResult dataTree_ProcessTxnResult0 = dataTree0.processTxn(txnHeader0, (Record) txnHeader0, txnDigest0);
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(0L, dataTree0.lastProcessedZxid);
      assertEquals(0, dataTree_ProcessTxnResult0.err);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      DataTree dataTree0 = new DataTree();
      dataTree0.getSessions();
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
      assertEquals(1371985504L, dataTree0.getTreeDigest());
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      FileTxnSnapLog fileTxnSnapLog0 = new FileTxnSnapLog((File) null, (File) null);
      ZKDatabase zKDatabase0 = new ZKDatabase(fileTxnSnapLog0);
      DataTree dataTree0 = zKDatabase0.createDataTree();
      dataTree0.getNodeCount();
      assertEquals(1371985504L, dataTree0.getTreeDigest());
      assertEquals(44L, dataTree0.cachedApproximateDataSize());
  }
}
