/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.jute.compiler;

import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;

/**
 * C++ Code generator front-end for Hadoop record I/O.
 */
class CGenerator {
    private String mName;
    private List<JFile> mInclFiles;
    private List<JRecord> mRecList;
    private final File outputDirectory;

    /** Creates a new instance of CppGenerator
     *
     * @param name possibly full pathname to the file
     * @param ilist included files (as JFile)
     * @param rlist List of records defined within this file
     * @param outputDirectory
     */
    CGenerator(String name, List<JFile> ilist, List<JRecord> rlist,
            File outputDirectory)
    {
        this.outputDirectory = outputDirectory;
        mName = (new File(name)).getName();
        mInclFiles = ilist;
        mRecList = rlist;
    }

    /**
     * Generate C++ code. This method only creates the requested file(s)
     * and spits-out file-level elements (such as include statements etc.)
     * record-level code is generated by JRecord.
     */
    void genCode() throws IOException {
        if (!outputDirectory.exists()) {
            if (!outputDirectory.mkdirs()) {
                throw new IOException("unable to create output directory "
                        + outputDirectory);
            }
        }

        try (FileWriter c = new FileWriter(new File(outputDirectory, mName + ".c"));
             FileWriter h = new FileWriter(new File(outputDirectory, mName + ".h"));
        ) {
            BufferedWriter bwh = new BufferedWriter(h);
	    BufferedWriter bwc = new BufferedWriter(c);

            bwh.write("/**\n");
            bwh.write("* Licensed to the Apache Software Foundation (ASF) under one\n");
            bwh.write("* or more contributor license agreements.  See the NOTICE file\n");
            bwh.write("* distributed with this work for additional information\n");
            bwh.write("* regarding copyright ownership.  The ASF licenses this file\n");
            bwh.write("* to you under the Apache License, Version 2.0 (the\n");
            bwh.write("* \"License\"); you may not use this file except in compliance\n");
            bwh.write("* with the License.  You may obtain a copy of the License at\n");
            bwh.write("*\n");
            bwh.write("*     http://www.apache.org/licenses/LICENSE-2.0\n");
            bwh.write("*\n");
            bwh.write("* Unless required by applicable law or agreed to in writing, software\n");
            bwh.write("* distributed under the License is distributed on an \"AS IS\" BASIS,\n");
            bwh.write("* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
            bwh.write("* See the License for the specific language governing permissions and\n");
            bwh.write("* limitations under the License.\n");
            bwh.write("*/\n");
            bwh.write("\n");

            bwc.write("/**\n");
            bwc.write("* Licensed to the Apache Software Foundation (ASF) under one\n");
            bwc.write("* or more contributor license agreements.  See the NOTICE file\n");
            bwc.write("* distributed with this work for additional information\n");
            bwc.write("* regarding copyright ownership.  The ASF licenses this file\n");
            bwc.write("* to you under the Apache License, Version 2.0 (the\n");
            bwc.write("* \"License\"); you may not use this file except in compliance\n");
            bwc.write("* with the License.  You may obtain a copy of the License at\n");
            bwc.write("*\n");
            bwc.write("*     http://www.apache.org/licenses/LICENSE-2.0\n");
            bwc.write("*\n");
            bwc.write("* Unless required by applicable law or agreed to in writing, software\n");
            bwc.write("* distributed under the License is distributed on an \"AS IS\" BASIS,\n");
            bwc.write("* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
            bwc.write("* See the License for the specific language governing permissions and\n");
            bwc.write("* limitations under the License.\n");
            bwc.write("*/\n");
            bwc.write("\n");

            bwh.write("#ifndef __" + mName.toUpperCase().replace('.', '_') + "__\n");
            bwh.write("#define __" + mName.toUpperCase().replace('.', '_') + "__\n");

            h.write("#include \"recordio.h\"\n");
            for (Iterator<JFile> i = mInclFiles.iterator(); i.hasNext(); ) {
                JFile f = i.next();
                bwh.write("#include \"" + f.getName() + ".h\"\n");
            }
            // required for compilation from C++
            bwh.write("\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

            bwc.write("#include <stdlib.h>\n"); // need it for calloc() & free()
            bwc.write("#include \"" + mName + ".h\"\n\n");

            for (Iterator<JRecord> i = mRecList.iterator(); i.hasNext(); ) {
                JRecord jr = i.next();
                jr.genCCode(h, c);
            }

            bwh.write("\n#ifdef __cplusplus\n}\n#endif\n\n");
            bwh.write("#endif //" + mName.toUpperCase().replace('.', '_') + "__\n");
        }
    }
}
