<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_242) on Mon May 04 15:08:51 GMT 2020 -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Uses of Class org.apache.zookeeper.CreateMode (Apache ZooKeeper - Server 3.5.8 API)</title>
<meta name="date" content="2020-05-04">
<link rel="stylesheet" type="text/css" href="../../../../stylesheet.css" title="Style">
<script type="text/javascript" src="../../../../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="Uses of Class org.apache.zookeeper.CreateMode (Apache ZooKeeper - Server 3.5.8 API)";
        }
    }
    catch(err) {
    }
//-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../../overview-summary.html">Overview</a></li>
<li><a href="../package-summary.html">Package</a></li>
<li><a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">Class</a></li>
<li class="navBarCell1Rev">Use</li>
<li><a href="../package-tree.html">Tree</a></li>
<li><a href="../../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../../index-all.html">Index</a></li>
<li><a href="../../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev</li>
<li>Next</li>
</ul>
<ul class="navList">
<li><a href="../../../../index.html?org/apache/zookeeper/class-use/CreateMode.html" target="_top">Frames</a></li>
<li><a href="CreateMode.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<div class="header">
<h2 title="Uses of Class org.apache.zookeeper.CreateMode" class="title">Uses of Class<br>org.apache.zookeeper.CreateMode</h2>
</div>
<div class="classUseContainer">
<ul class="blockList">
<li class="blockList">
<table class="useSummary" border="0" cellpadding="3" cellspacing="0" summary="Use table, listing packages, and an explanation">
<caption><span>Packages that use <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Package</th>
<th class="colLast" scope="col">Description</th>
</tr>
<tbody>
<tr class="altColor">
<td class="colFirst"><a href="#org.apache.zookeeper">org.apache.zookeeper</a></td>
<td class="colLast">&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><a href="#org.apache.zookeeper.server">org.apache.zookeeper.server</a></td>
<td class="colLast">
<div class="block">ZooKeeper server theory of operation</div>
</td>
</tr>
</tbody>
</table>
</li>
<li class="blockList">
<ul class="blockList">
<li class="blockList"><a name="org.apache.zookeeper">
<!--   -->
</a>
<h3>Uses of <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a> in <a href="../../../../org/apache/zookeeper/package-summary.html">org.apache.zookeeper</a></h3>
<table class="useSummary" border="0" cellpadding="3" cellspacing="0" summary="Use table, listing methods, and an explanation">
<caption><span>Methods in <a href="../../../../org/apache/zookeeper/package-summary.html">org.apache.zookeeper</a> that return <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tbody>
<tr class="altColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></code></td>
<td class="colLast"><span class="typeNameLabel">CreateMode.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/CreateMode.html#fromFlag-int-">fromFlag</a></span>(int&nbsp;flag)</code>
<div class="block">Map an integer value to a CreateMode value</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></code></td>
<td class="colLast"><span class="typeNameLabel">CreateMode.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/CreateMode.html#fromFlag-int-org.apache.zookeeper.CreateMode-">fromFlag</a></span>(int&nbsp;flag,
        <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;defaultMode)</code>
<div class="block">Map an integer value to a CreateMode value</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></code></td>
<td class="colLast"><span class="typeNameLabel">CreateMode.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/CreateMode.html#valueOf-java.lang.String-">valueOf</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;name)</code>
<div class="block">Returns the enum constant of this type with the specified name.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>[]</code></td>
<td class="colLast"><span class="typeNameLabel">CreateMode.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/CreateMode.html#values--">values</a></span>()</code>
<div class="block">Returns an array containing the constants of this enum type, in
the order they are declared.</div>
</td>
</tr>
</tbody>
</table>
<table class="useSummary" border="0" cellpadding="3" cellspacing="0" summary="Use table, listing methods, and an explanation">
<caption><span>Methods in <a href="../../../../org/apache/zookeeper/package-summary.html">org.apache.zookeeper</a> with parameters of type <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tbody>
<tr class="altColor">
<td class="colFirst"><code><a href="../../../../org/apache/zookeeper/Transaction.html" title="class in org.apache.zookeeper">Transaction</a></code></td>
<td class="colLast"><span class="typeNameLabel">Transaction.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/Transaction.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode)</code>&nbsp;</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a></code></td>
<td class="colLast"><span class="typeNameLabel">ZooKeeper.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode)</code>
<div class="block">Create a node with the given path.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/Op.html" title="class in org.apache.zookeeper">Op</a></code></td>
<td class="colLast"><span class="typeNameLabel">Op.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/Op.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode)</code>
<div class="block">Constructs a create operation.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>void</code></td>
<td class="colLast"><span class="typeNameLabel">ZooKeeper.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-org.apache.zookeeper.AsyncCallback.Create2Callback-java.lang.Object-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode,
      <a href="../../../../org/apache/zookeeper/AsyncCallback.Create2Callback.html" title="interface in org.apache.zookeeper">AsyncCallback.Create2Callback</a>&nbsp;cb,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</a>&nbsp;ctx)</code>
<div class="block">The asynchronous version of create.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>void</code></td>
<td class="colLast"><span class="typeNameLabel">ZooKeeper.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-org.apache.zookeeper.AsyncCallback.Create2Callback-java.lang.Object-long-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode,
      <a href="../../../../org/apache/zookeeper/AsyncCallback.Create2Callback.html" title="interface in org.apache.zookeeper">AsyncCallback.Create2Callback</a>&nbsp;cb,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</a>&nbsp;ctx,
      long&nbsp;ttl)</code>
<div class="block">The asynchronous version of create with ttl.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>void</code></td>
<td class="colLast"><span class="typeNameLabel">ZooKeeper.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-org.apache.zookeeper.AsyncCallback.StringCallback-java.lang.Object-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode,
      <a href="../../../../org/apache/zookeeper/AsyncCallback.StringCallback.html" title="interface in org.apache.zookeeper">AsyncCallback.StringCallback</a>&nbsp;cb,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</a>&nbsp;ctx)</code>
<div class="block">The asynchronous version of create.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/Op.html" title="class in org.apache.zookeeper">Op</a></code></td>
<td class="colLast"><span class="typeNameLabel">Op.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/Op.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-long-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode,
      long&nbsp;ttl)</code>
<div class="block">Constructs a create operation.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a></code></td>
<td class="colLast"><span class="typeNameLabel">ZooKeeper.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-org.apache.zookeeper.data.Stat-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode,
      <a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/Stat.html?is-external=true" title="class or interface in org.apache.zookeeper.data">Stat</a>&nbsp;stat)</code>
<div class="block">Create a node with the given path and returns the Stat of that node.</div>
</td>
</tr>
<tr class="altColor">
<td class="colFirst"><code><a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a></code></td>
<td class="colLast"><span class="typeNameLabel">ZooKeeper.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-org.apache.zookeeper.data.Stat-long-">create</a></span>(<a href="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</a>&nbsp;path,
      byte[]&nbsp;data,
      <a href="https://docs.oracle.com/javase/8/docs/api/java/util/List.html?is-external=true" title="class or interface in java.util">List</a>&lt;<a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/ACL.html?is-external=true" title="class or interface in org.apache.zookeeper.data">ACL</a>&gt;&nbsp;acl,
      <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;createMode,
      <a href="http://zookeeper.apache.org/zookeeper-jute/apidocs/org/apache/zookeeper/data/Stat.html?is-external=true" title="class or interface in org.apache.zookeeper.data">Stat</a>&nbsp;stat,
      long&nbsp;ttl)</code>
<div class="block">same as <a href="../../../../org/apache/zookeeper/ZooKeeper.html#create-java.lang.String-byte:A-java.util.List-org.apache.zookeeper.CreateMode-org.apache.zookeeper.data.Stat-"><code>ZooKeeper.create(String, byte[], List, CreateMode, Stat)</code></a> but
 allows for specifying a TTL when mode is <a href="../../../../org/apache/zookeeper/CreateMode.html#PERSISTENT_WITH_TTL"><code>PERSISTENT_WITH_TTL</code></a>
 or <a href="../../../../org/apache/zookeeper/CreateMode.html#PERSISTENT_SEQUENTIAL_WITH_TTL"><code>PERSISTENT_SEQUENTIAL_WITH_TTL</code></a>.</div>
</td>
</tr>
<tr class="rowColor">
<td class="colFirst"><code>static <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></code></td>
<td class="colLast"><span class="typeNameLabel">CreateMode.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/CreateMode.html#fromFlag-int-org.apache.zookeeper.CreateMode-">fromFlag</a></span>(int&nbsp;flag,
        <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;defaultMode)</code>
<div class="block">Map an integer value to a CreateMode value</div>
</td>
</tr>
</tbody>
</table>
</li>
<li class="blockList"><a name="org.apache.zookeeper.server">
<!--   -->
</a>
<h3>Uses of <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a> in <a href="../../../../org/apache/zookeeper/server/package-summary.html">org.apache.zookeeper.server</a></h3>
<table class="useSummary" border="0" cellpadding="3" cellspacing="0" summary="Use table, listing methods, and an explanation">
<caption><span>Methods in <a href="../../../../org/apache/zookeeper/server/package-summary.html">org.apache.zookeeper.server</a> with parameters of type <a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a></span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tbody>
<tr class="altColor">
<td class="colFirst"><code>static void</code></td>
<td class="colLast"><span class="typeNameLabel">EphemeralType.</span><code><span class="memberNameLink"><a href="../../../../org/apache/zookeeper/server/EphemeralType.html#validateTTL-org.apache.zookeeper.CreateMode-long-">validateTTL</a></span>(<a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">CreateMode</a>&nbsp;mode,
           long&nbsp;ttl)</code>
<div class="block">Utility to validate a create mode and a ttl</div>
</td>
</tr>
</tbody>
</table>
</li>
</ul>
</li>
</ul>
</div>
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../../overview-summary.html">Overview</a></li>
<li><a href="../package-summary.html">Package</a></li>
<li><a href="../../../../org/apache/zookeeper/CreateMode.html" title="enum in org.apache.zookeeper">Class</a></li>
<li class="navBarCell1Rev">Use</li>
<li><a href="../package-tree.html">Tree</a></li>
<li><a href="../../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../../index-all.html">Index</a></li>
<li><a href="../../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li>Prev</li>
<li>Next</li>
</ul>
<ul class="navList">
<li><a href="../../../../index.html?org/apache/zookeeper/class-use/CreateMode.html" target="_top">Frames</a></li>
<li><a href="CreateMode.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
<p class="legalCopy"><small>Copyright &#169; 2008&#x2013;2020 <a href="https://www.apache.org/">The Apache Software Foundation</a>. All rights reserved.</small></p>
</body>
</html>
