version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: vijay-test

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v1
